apiVersion: apps/v1
kind: Deployment
metadata:
  name: pp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pp-backend
  template:
    metadata:
      labels:
        app: pp-backend
    spec:
      containers:
        - name: app-backend
          image: avasiliev/promocode-factory-api:111.111
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: app-backend